### ISSUE TITLE
SIG Reviewer/Maintainer Nomination

### ISSUE THREAD

**Issue by junbo75** [o3de/sig-network#11]
### Nomination Guidelines
**Reviewer Nomination Requirements**
* 6+ contributions successfully submitted to O3DE
* 100+ lines of code changed across all contributions submitted to O3DE
* 2+ O3DE Reviewers or Maintainers that support promotion from Contributor to Reviewer
* Requirements to retain the Reviewer role: 4+ Pull Requests reviewed per month

**Maintainer Nomination Requirements**
* Has been a Reviewer for 2+ months
* 8+ reviewed Pull Requests in the previous 2 months
* 200+ lines of code changed across all reviewed Pull Request
* 2+ O3DE Maintainers that support the promotion from Reviewer to Maintainer
* Requirements to retain the Reviewer role: 4+ Pull Requests reviewed per month

-------
##### Fill out the template below including nominee GitHub user name, desired role and personal GitHub profile
-------------------

I would like to nominate: junbo75, to become a Maintainer on behalf of sig-network. I verify that they have fulfilled the prerequisites for this role.

* Nominee's GitHub Profile https://github.com/junbo75

*Reviewers & Maintainers that support this nomination should comment in this issue.*

**Comment by lmbr-pip** [comment]
I support @junbo75 for maintainer

**Comment by AMZN-alexpete** [comment]
+1 I also support junbo75 for maintainer

**Comment by AMZN-puvvadar** [comment]
I support junbo75 for mainainer.
