### ISSUE TITLE
SIG-Networking 11/30 release notes

### ISSUE THREAD

**Issue by Ulrick28** [o3de/sig-network#18]
Please fill any info related to the below for the 11/30 release notes: Note this has a due date of Friday Nov 12th, 2021

(Note: Notes should cover July 6th to Nov 12th)

 * Features
 * Bug fixes (GHI list if possible)
 * Deprecationa
 * Known issues

### Cloud Services
* AWS GameLift Gem completed and out of preview
     * Added Linux and FlexMatch support

### Networking
* Added support for Network Hierarchy of Entities - Provides a way to group network entities to combine their multiplayer input processing.
     * RFC: https://github.com/o3de/sig-network/blob/main/rfcs/rfc-net-20211005-2-entityhierarchies.md
* Added support for networking scripting inputs - Enables extensive use of script canvas to build and run networking scripts
     * RFC:  https://github.com/o3de/sig-network/blob/main/rfcs/rfc-net-20211005-1-inputscripting.md
* Added Linux support for Client and Server targets in [O3DE-MultiplayerSample](https://github.com/o3de/o3de-multiplayersample)
     * MultiplayerSample.GameLauncher and MultiplayerSample.ServerLauncher can be built and executed on Linux

## Bug Fixes
* Fixed dependencies for networking that could crash the Editor: https://github.com/o3de/o3de/issues/5277 
* Enabled tests for HttpRequestor gem: https://github.com/o3de/o3de/issues/4687
* Changed the serialization format for networking to binary to save space and time: https://github.com/o3de/o3de/issues/4608
* Multiplayer NetworkInput Silently Fails Unless LocalPredictionPlayerInputComponent is Attached: https://github.com/o3de/o3de/issues/3155

(Add MPS updates here)

## Deprecations
* None

## Known issues
* TBD

**Comment by AMZN-Olex** [comment]
- Features
     - **Network Hierarchy of Entities**
          - Provides a way to group network entities to combine their multiplayer input processing
          - RFC: https://github.com/o3de/sig-network/issues/5
     - **Linux support** for Client and Server targets in O3DE-MultiplayerSample
          -  MultiplayerSample.GameLauncher and MultiplayerSample.ServerLauncher are compilable and executable on Linux           
          -  Tested on Ubuntu 20

**Comment by lmbr-pip** [comment]
Added these known issues 

* Server launchers are manually relocatable. There is currently no automated build or asset layout generation. See instructions here https://o3de.org/docs/user-guide/gems/reference/aws/aws-gamelift/build-packaging-for-windows/ and https://o3de.org/docs/user-guide/gems/reference/aws/aws-gamelift/build-packaging-for-linux (can ignore GameLift specific steps if not relocating to GameLift instances).
* Monolithic release server builds are currently not supported.
* Network entity hierarchies are limited to hierarchies with max count of 16 entities.
* imgui keyboard not working in server launcher
* console is not working on server launcher.
* Legacy GridMate networking layer is still shipped in code, its not recommended for use for networking. See new networking components: https://o3de.org/docs/user-guide/networking/
* Mouse controls are not friendly to working over remote desktop connections. See https://github.com/o3de/o3de/issues/5339. You may need to turn off “'Capture Mouse Cursor” mode in the editor (*Edit -> Editor Settings -> Global Preferences->Camera)*

All release notes are not moved to staging area, sig-docs-community controls further updates.

Resolving story as completed
