### ISSUE TITLE
SIG Maintainer Nomination

### ISSUE THREAD

**Issue by AMZN-Gene** [o3de/sig-network#21]
### Reviewer/Maintainer Nomination

I would like to nominate: AMZN-Gene, to become a Maintainer on behalf of sig-networking. I verify that I have fulfilled the prerequisites for this role.

* Nominee's GitHub Profile https://github.com/AMZN-Gene

**Maintainer Nomination Requirements**
* Has been a Reviewer for 2+ months
* 8+ reviewed Pull Requests in the previous 2 months
* 200+ lines of code changed across all reviewed Pull Request
* 2+ O3DE Maintainers that support the promotion from Reviewer to Maintainer
* Requirements to retain the Reviewer role: 4+ Pull Requests reviewed per month

*Reviewers & Maintainers that support this nomination should comment in this issue.*

**Comment by lmbr-pip** [comment]
+1 - I support Gene for maintainer

**Comment by SergeyAMZN** [comment]
I support Gene for maintainer

**Comment by kberg-amzn** [comment]
Support 👍

**Comment by lmbr-pip** [comment]
Approved at SIG-network Nov 23 2021
