### ISSUE TITLE
SIG Reviewer Nomination for `allisaurus`

### ISSUE THREAD

**Issue by allisaurus** [o3de/sig-network#25]
I would like to nominate: [**allisaurus**](https://github.com/allisaurus) (myself), to become a ***Reviewer*** on behalf of ***SIG-Network***. I verify that I have fulfilled the prerequisites for this role.

* Nominee's GitHub Profile : https://github.com/allisaurus 

**Reviewer Nomination Requirements**
* 6+ contributions successfully submitted to O3DE
  * https://github.com/pulls?q=is%3Apr+archived%3Afalse+user%3Ao3de+is%3Aclosed+author%3Aallisaurus
* 100+ lines of code changed across all contributions submitted to O3DE
  * above PRs (at time of this writing) account for +250 lines of code changes
* 2+ O3DE Reviewers or Maintainers that support promotion from Contributor to Reviewer
  * @lmbr-pip, @junbo75 & @onecent1101 support this nomination. 

*Reviewers & Maintainers that support this nomination should comment in this issue.*

**Comment by onecent1101** [comment]
I support allisaurus for reviewer.

**Comment by junbo75** [comment]
I support @allisaurus for reviewer.

**Comment by lmbr-pip** [comment]
I support this nomination.

**Comment by lmbr-pip** [comment]
Reviewer nomination accepted at SIG meeting 12/7/2021. SIG chair(s) to promote.
