### ISSUE TITLE
SIG Reviewer/Maintainer Nomination - AMZN-puvvadar

### ISSUE THREAD

**Issue by lmbr-pip** [o3de/sig-network#60]
### Nomination Guidelines

**Maintainer Nomination Requirements**
* Has been a Reviewer for 2+ months
* 8+ reviewed Pull Requests in the previous 2 months
* 200+ lines of code changed across all reviewed Pull Request
* 2+ O3DE Maintainers that support the promotion from Reviewer to Maintainer
* Requirements to retain the Reviewer role: 4+ Pull Requests reviewed per month
---------------------------

I would like to nominate: [AMZN-puvvadar](https://github.com/AMZN-puvvadar), to become a ***Maintainer*** on behalf of ***sig-Network**. I verify that they have fulfilled the prerequisites for this role.

* Nominee's GitHub Profile ***https://github.com/AMZN-puvvadar)***

*Reviewers & Maintainers that support this nomination should comment in this issue.*

**Comment by AMZN-puvvadar** [comment]
I accept the nomination.

**Comment by AMZN-Olex** [comment]
+1

**Comment by lmbr-pip** [comment]
SIG accepted maintainer
