### ISSUE TITLE
SIG Reviewer/Maintainer Nomination - AMZN-Olex

### ISSUE THREAD

**Issue by lmbr-pip** [o3de/sig-network#61]
### Nomination Guidelines

**Maintainer Nomination Requirements**
* Has been a Reviewer for 2+ months
* 8+ reviewed Pull Requests in the previous 2 months
* 200+ lines of code changed across all reviewed Pull Request
* 2+ O3DE Maintainers that support the promotion from Reviewer to Maintainer
* Requirements to retain the Reviewer role: 4+ Pull Requests reviewed per month

-------------------

I would like to nominate: ***https://github.com/AMZN-Olex***, to become a ***Maintainer*** on behalf of ***sig-network***. I verify that they have fulfilled the prerequisites for this role.

* Nominee's GitHub Profile ***[< https://github.com/ githubsername >](https://github.com/AMZN-Olex)***

*Reviewers & Maintainers that support this nomination should comment in this issue.*

**Comment by AMZN-Olex** [comment]
I accept the nomination. Thank you!

**Comment by AMZN-puvvadar** [comment]
+1, I support the nomination.

**Comment by lmbr-pip** [comment]
SIG accepted maintainer
