### ISSUE TITLE
Create Roadmap View

### ISSUE THREAD

**Issue by vincent6767** [o3de/sig-network#90]
Hi! SIG release is working to help the O3DE community to get visibility of the O3DE roadmap. Full context can be read here: https://github.com/o3de/sig-release/issues/79. 

In order to achieve that goal, we need your help to create the roadmap for your SIG by **February 6th, 2023**, and start giving brief updates about the roadmap items at the **Joint TSC meeting on February 28th, 2023**. Instruction to create the roadmap view can be read in the RFC section "Roadmap Review in TSC monthly meeting".

Let me know if you have any concerns with the dates or any questions about the ask!

**Comment by lmbr-pip** [comment]
@vincent6767 We had previously created https://github.com/orgs/o3de/projects/22

**Comment by vincent6767** [comment]
Thanks for the updates. Let me know if you have any questions about the new format! @lmbr-pip

**Comment by vincent6767** [comment]
Hi @lmbr-pip Are there any updates for the roadmap? I see the issues in the roadmap still missing the kind/roadmap.

**Comment by lmbr-pip** [comment]
Have added kind/roadmap to items.

Btw, not everything on roadmap is always a feature, somethings are critical bug fixes or security updates. It gets confusing when kind/bug feature/roadmap labels are on these critical bugs. To me there should be space for both types of items on the roadmap.

**Comment by vincent6767** [comment]
Thanks for the help! In my opinion, it's not confusing as essentially the roadmap item is an issue that shows in the O3DE public roadmap and worth others for knowing. Thoughts?
