### ISSUE TITLE
SIG-Network Nominations 1/23 - 2/3 — Elections 2/6 - 2/10

### ISSUE THREAD

**Issue by allisaurus** [o3de/sig-network#91]
## SIG chair / co-chair roles
The chair and co-chair serve equivalent roles in the governance of the SIG and are only differentiated by title in that the highest vote-getter is the chair and the second-highest is the co-chair. The chair and co-chair are expected to govern together in an effective way and split their responsibilities to make sure that the SIG operates smoothly and has the availability of a chairperson at any time.

Unless distinctly required, the term "chairperson" refers to either/both of the chair and co-chair. If a chair or co-chair is required to perform a specific responsibility for the SIG they will always be addressed by their official role title.

In particular, if both chairpersons would be unavailable during a period of time, the chair is considered to be an on-call position during this period. As the higher vote-getter they theoretically represent more of the community and should perform in that capacity under extenuating circumstances. This means that if there is an emergency requiring immediate action from the SIG, the chair will be called to perform a responsibility.

### Responsibilities
See chair and co-chair responsibilities as outlined in the [SIG-Network Charter](https://github.com/o3de/sig-network/blob/main/governance/SIG%20Network%20Charter.md#additional-responsibilities-of-chairs).

## Nomination
Nomination may either be by a community member or self-nomination. A nominee may withdraw from the election at any time for any reason until the election starts on 2/6/2023.

### Nomination requirements
The only other nomination requirement is that the nominee agrees to be able to perform their required duties and has the availability to do so, taking into account the fact that another chairperson will always be available as a point of contact.

### How to nominate
Nominations will be accepted for 2 weeks from **January 23, 2023 12:00PM PT to February 3, 2023 12:00PM PT**.
Nominate somebody (including yourself) by responding to this issue with:

* A statement that the nominee should be nominated for a chair position in SIG-Network. Nominees are required to provide a statement that they understand the responsibilities and requirements of the role, and promise to faithfully fulfill them and follow all contributor requirements for O3DE.
* The name under which the nominee should be addressed. Nominees are allowed to contact the election proctor to have this name changed.
* The GitHub username of the nominee (self-nominations need not include this; it's on your post.)
* Nominee's Discord username (sorry, but you must be an active Discord user if you are a chairperson.)

### Election process
The election will be conducted for one week from **February 6, 2023 12:00PM PT to February 10, 2023 12:00PM PT** and held through an online poll. Votes will be anonymous and anyone invested in the direction of O3DE and SIG-Network may vote. If you choose to vote, we ask that you be familiar with the nominees.

If there is a current interim chair, they will announce the results in the Discord SIG channel as well as the SIG O3DE mailing list no later than **February 13, 2023 1:00PM PT**. If there is no interim chair, the executive director will announce the results utilizing the same communication channels. At that time if there is a dispute over the result or concern over vote tampering, voting information will be made public to the extent that it can be exported from the polling system and the SIG will conduct an independent audit under the guidance of a higher governing body in the foundation.

The elected chairpersons will begin serving their term on **February 14, 2023 at 10:00AM PT**. Tentatively SIG chairs will be elected on a yearly basis.

**Comment by lmbr-pip** [comment]
Thanks for being our election coordinator @allisaurus 

As current chair am happy to continue being chai or co-chair if we need someone to fill either role. I would however be delighted to be replaced and really want to encourage others with a passion to lead the SIG to step up.
 
Can see my contributions to O3DE, https://github.com/pulls?q=is%3Apr+author%3Almbr-pip+archived%3Afalse+user%3Ao3de+. I do not get a lot of time for actual code contributions to O3DE but it demonstrates some contributions to the areas SIG/Network aligns with.

I understand the responsibilities and requirements of the role, and promise to faithfully fulfill them and follow all contributor requirements for O3DE.  I am Seapip [Amazon] on Discord and go by Pip Potter.

**Comment by allisaurus** [comment]
I'd like to nominate @kberg-amzn  as a chair. As current co-chair he's familiar with what's needed to fulfill the role and has the expertise needed to guide this SIG.

**Comment by kberg-amzn** [comment]
I understand and accept the responsibilities of the role.

**Comment by allisaurus** [comment]
As confirmed with @lmbr-pip and @kberg-amzn , they will continue on as Chair and Co-chair (respectively). This issue can be closed.
